"""unify model attributes to snake_case

Revision ID: 33862fb11f93
Revises: 3cd88818bbd3
Create Date: 2025-09-21 00:31:25.089906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33862fb11f93'
down_revision = '3cd88818bbd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trade_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('contract_id', sa.String(length=20), nullable=False))
        batch_op.drop_constraint(batch_op.f('position_tradeId_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'trade', ['trade_id'], ['id'])
        batch_op.drop_column('contractId')
        batch_op.drop_column('tradeId')

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profit_mechanism', sa.String(length=100), nullable=False))
        batch_op.drop_column('profitMechanism')

    with op.batch_alter_table('trade_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trade_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('trade_log_tradeId_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'trade', ['trade_id'], ['id'])
        batch_op.drop_column('tradeId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tradeId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('trade_log_tradeId_fkey'), 'trade', ['tradeId'], ['id'])
        batch_op.drop_column('trade_id')

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profitMechanism', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('profit_mechanism')

    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tradeId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('contractId', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('position_tradeId_fkey'), 'trade', ['tradeId'], ['id'])
        batch_op.drop_column('contract_id')
        batch_op.drop_column('trade_id')

    # ### end Alembic commands ###
